---
image: node:lts
pages:
  tags:
    - gitlab-org
  script:
    - npm install
    - npm run build
    - echo "Pages will be deployed to $CI_PAGES_URL."
  artifacts:
    paths:
      # The folder that contains the built files to be published. This
      # must be called "public".
      - public
